name: e2e_tests
description: equatable_annotations example
version: 1.0.1

publish_to: "none"

environment:
  sdk: ^3.9.0

dependencies:
  equatable_annotations:
  equatable: ^2.0.7

dev_dependencies:
  build_runner: ^2.10.4
  build_test: ^3.5.4
  equatable_gen:
  lints: ^6.0.0
  test: ^1.28.0
  generator_test: ^0.6.0

scripts: scripts.yaml
