name: equatable_gen
description: Automatically creates 'props' getters for classes using the equatable package.
version: 1.2.0
homepage: https://github.com/mrgnhnt96/equatable_gen
issue_tracker: https://github.com/mrgnhnt96/equatable_gen/issues

funding:
  - https://github.com/sponsors/mrgnhnt96

topics:
  - equatable
  - equality
  - equals
  - props
  - generator

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ">=8.0.0 <10.0.0"
  equatable_annotations: ^1.2.0
  build: ^4.0.3
  code_builder: ^4.11.0
  change_case: ^2.2.0
  dart_style: ^3.1.3
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  meta: ^1.17.0
  source_gen: ^4.1.1
  path: ^1.9.1
  source_span: ^1.10.1
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.10.4
  build_test: ^3.5.4
  generator_test: ^0.6.0
  json_serializable: ^6.11.3
  lints: ^6.0.0
  test: ^1.28.0
