name: equatable_annotations
description: Provides annotations for the 'equatable_gen' code generator, used with the 'equatable' package
version: 1.3.0
homepage: https://github.com/mrgnhnt96/equatable_gen
issue_tracker: https://github.com/mrgnhnt96/equatable_gen/issues

funding:
  - https://github.com/sponsors/mrgnhnt96

topics:
  - equatable
  - equality
  - equals
  - props
  - generator

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0

dev_dependencies:
  equatable: ^2.0.7
  lints: ^6.0.0
  test: ^1.28.0
