name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4

      - id: setup_dart
        name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Sip
        run: dart pub global activate sip_cli

      - name: Install Depedencies
        run: |
          cd equatable_annotations || exit 1
          dart pub get
          cd ../ || exit 1

          cd equatable_gen || exit 1
          dart pub get

      - name: Check the formatting of one or more Dart files
        run: |
          set -e

          cd equatable_annotations || exit 1
          dart format . --set-exit-if-changed
          cd ../ || exit 1

          cd equatable_gen || exit 1
          dart format . --set-exit-if-changed

      - name: Analyze the project's Dart code
        run: |
          set -e

          cd equatable_annotations || exit 1
          dart analyze . --fatal-warnings
          cd ../ || exit 1

          cd equatable_gen || exit 1
          dart analyze . --fatal-warnings

      - name: Run Gen tests
        run: sip run test gen

      - name: Run E2E tests
        run: sip run test e2e
